import type { Metadata } from "next";
import { Geist, Rethink_Sans, Marck_Script } from "next/font/google";
import "./globals.css";
import Menu from "@/components/Menu";
import Loading from "@/components/Loading";
import { SessionProvider } from "next-auth/react";
import { QueryProvider } from "@/providers/QueryPovider";
import { Toaster } from "@/components/Toaster";

const geistSans = Geist({
  variable: "--font-geist",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "600", "700"],
});

const rethink_sans = Rethink_Sans({
  variable: "--font-rethink",
  subsets: ["latin"],
  weight: ["400", "600", "700"],
});

const marck_script = Marck_Script({
  weight: ["400"],
  subsets: ["latin"],
  variable: "--font-marck-script",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt">
      <body
        className={`${geistSans.variable} ${rethink_sans.variable} ${marck_script.variable} antialiased`}
      >
        <Loading />
        <SessionProvider>

          <QueryProvider>
            <Menu />
            {children}
          </QueryProvider>
          <Toaster />
        </SessionProvider>
      </body>
    </html>
  );
}
